---

default:
  tags:
    - any-image-allowed

stages:
  - test

test_job:
  stage: test
  image: python:3.11-slim
  before_script:
    - apt-get update && apt-get install -y make
    - python --version
  script:
    - pip install -e ".[dev]"
    - ENV_FILE=.env.test.lite pytest tests
