---

default:
  tags:
    - any-image-allowed

stages:
  - test
  - docs

test_job:
  stage: test
  image: python:3.11-slim
  before_script:
    - apt-get update && apt-get install -y make
    - python --version
  script:
    - pip install -e ".[dev]"
    - ENV_FILE=.env.test.lite pytest tests

generate_mkdocs:
  before_script: []
  stage: docs
  image: hub.cert.kit.edu:5000/mkdocs
  script:
    - source /root/.venv/bin/activate; PYTHONPATH=src mkdocs build
  artifacts:
    paths:
      - site
  services:
    - name: plantuml/plantuml-server
      alias: plantuml
