default:
  tags:
      - kgr1-instance-mini

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  # CI_DEBUG_SERVICES: true
  PYTHONUNBUFFERED: true

stages:
  - build_image
  - test
  - coverage
  - docs
  - release

cache:
  paths:
    - .cache/pip

build_image:
  needs: []
  before_script: []
  stage: build_image
  tags:
    - kgr1-instance-standard
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - >-
      echo '{"auths":{"https://registry.cert.kit.edu/v2/":{"auth": "'$(echo -n ${REGISTRY_USER}:${REGISTRY_PASSWORD} | base64 -w 0)'" }}}' > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/lib:${CI_COMMIT_BRANCH}
      --destination ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/lib:${CI_COMMIT_SHA}

compare_db:
  tags:
      - kgr1-instance-standard
  stage: test
  image: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/lib:${CI_COMMIT_SHA}
  script:
    - while [ ! -f "$MISP_READY_FILE" ]; do sleep 10; done
    - python -m mmisp.db.print_changes
  services:
    - name: mariadb:latest
      alias: db
      variables:
        HEALTHCHECK_TCP_PORT: 3306
    - name: registry.cert.kit.edu/public-gitlab-ci/misp-core:latest
      alias: misp-core
      variables:
        MYSQL_PASSWORD: misp
        MYSQL_USER: root
        DISABLE_SSL_REDIRECT: true
        HEALTHCHECK_TCP_PORT: 80
        ENABLE_DB_SETTINGS: "false"
        DEBUG: 1
    - name: valkey/valkey:7.2
      command: ["--requirepass 1CA9kMhX6mcuhRlRAptZdQieSX6u25SJ"]
      alias: redis
      variables:
        HEALTHCHECK_TCP_PORT: 6379
  variables:
    MARIADB_ROOT_PASSWORD: misp
    MARIADB_DATABASE: misp
    REDIS_PASSWORD: 1CA9kMhX6mcuhRlRAptZdQieSX6u25SJ
    DATABASE_URL: "mysql+aiomysql://root:misp@db:3306/misp"
    HASH_SECRET: hO1cfVGuFGsNwGvw9xzxnq5sU
    WORKER_KEY: GcXh5TAq8RxYvdTpdioP0nI20Le
    OWN_URL: http://localhost:4000
    WORKER_URL: https://worker.mmisp.service
    DASHBOARD_URL: https://dashboard.mmisp.service
    DEBUG: true
    MISP_READY_FILE: '${CI_PROJECT_DIR}/misp_ready'

pytest:
  parallel: 1
  stage: test
  image: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/lib:${CI_COMMIT_SHA}
  script:
    - pytest --test-group-count $CI_NODE_TOTAL --test-group=$CI_NODE_INDEX  --cov --cov-report= tests/
  variables:
    COVERAGE_FILE: ".coverage.${CI_NODE_INDEX}"
    DATABASE_URL: sqlite+aiosqlite:///mmisp-tests.db?check_same_thread=False
    HASH_SECRET: hO1cfVGuFGsNwGvw9xzxnq5sU
    WORKER_KEY: GcXh5TAq8RxYvdTpdioP0nI20Le
    OWN_URL: http://localhost:4000
    WORKER_URL: https://worker.mmisp.service
    DASHBOARD_URL: https://dashboard.mmisp.service
  artifacts:
    paths:
      - ".coverage.*"

pytest_coverage_combine:
  stage: coverage
  image: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/lib:${CI_COMMIT_SHA}
  script:
    - coverage combine
    - coverage xml
    - coverage report
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

mypy:
  stage: test
  image: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/lib:${CI_COMMIT_SHA}
  allow_failure: true
  script:
    - pip install "sqlalchemy>=2.0"
    - MYPYPATH=src mypy --explicit-package-bases src/mmisp/

ruff:
  stage: test
  image: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/lib:${CI_COMMIT_SHA}
  script:
    - ruff check
    - ruff format --check

generate_mkdocs:
  before_script: []
  stage: docs
  image: registry.cert.kit.edu/public-gitlab-ci/mkdocs
  script:
    - source /root/.venv/bin/activate; PYTHONPATH=src mkdocs build
  artifacts:
    paths:
      - site
  services:
    - name: plantuml/plantuml-server
      alias: plantuml


pypi_release:
  before_script: []
  stage: release
  image: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/lib:${CI_COMMIT_SHA}
  script:
    - python -m build --sdist
    - twine upload dist/mmisp_lib-*.tar.gz
  artifacts:
    paths:
      - site
  rules:
    - if: $CI_PROJECT_NAMESPACE != "kit/kit-cert/mmisp"
      when: never
    - if: $CI_COMMIT_BRANCH != "main"
      when: never
    - when: manual
  variables:
    TWINE_USERNAME: "__token__"
    TWINE_PASSWORD: "${PYPI_TOKEN}"
