FROM python:3.11

ARG DOCKER_USER=mmisp
ARG INSTALL_LIB=false
ARG LIB_REPO_URL
ARG BRANCH

RUN groupadd "$DOCKER_USER"
RUN useradd -ms /bin/bash -g "$DOCKER_USER" "$DOCKER_USER"
USER $DOCKER_USER
WORKDIR /home/$DOCKER_USER

RUN pip install --upgrade pip

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PATH="/home/${DOCKER_USER}/.local/bin:${PATH}"

ADD --chown=$DOCKER_USER:$DOCKER_USER . ./
RUN pip install '.[dev]'
