version: "3.1"

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: misp
      MYSQL_DATABASE: misp
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 1s
      retries: 20

  success:
    container_name: success-check
    image: hello-world:latest
    depends_on:
      mysql:
        condition: service_healthy
