@startuml packages
set namespaceSeparator none
package "app.schemas.objects" as app.schemas.objects {
}
package "app.schemas.objects.create_object_body" as app.schemas.objects.create_object_body {
}
package "app.schemas.objects.delete_object_response" as app.schemas.objects.delete_object_response {
}
package "app.schemas.objects.get_added_object_response" as app.schemas.objects.get_added_object_response {
}
package "app.schemas.objects.get_object_response" as app.schemas.objects.get_object_response {
}
package "app.schemas.objects.search_objects_body" as app.schemas.objects.search_objects_body {
}
package "app.schemas.objects.search_objects_response" as app.schemas.objects.search_objects_response {
}
app.schemas.objects.get_added_object_response --> app.schemas.objects.search_objects_response
@enduml
