from pydantic import BaseModel, Field
from typing_extensions import Annotated


class GetDescribeTypesSaneDefaultsAttributes(BaseModel):
    default_category: str
    to_ids: int


class GetDescribeTypesCategoryTypeMappings(BaseModel):
    INTERNAL_REFERENCE: Annotated[list[str], Field(alias="Internal reference")] = [
        "text",
        "link",
        "comment",
        "other",
        "hex",
        "anonymised",
        "git-commit-id",
    ]
    TARGETING_DATA: Annotated[list[str], Field(alias="Targeting data")] = [
        "target-user",
        "target-email",
        "target-machine",
        "target-org",
        "target-location",
        "target-external",
        "comment",
        "anonymised",
    ]
    ANTIVIRUS_DETECTION: Annotated[list[str], Field(alias="Antivirus detection")] = [
        "link",
        "comment",
        "text",
        "hex",
        "attachment",
        "other",
        "anonymised",
    ]
    PAYLOAD_DELIVERY: Annotated[list[str], Field(alias="Payload delivery")] = [
        "md5",
        "sha1",
        "sha224",
        "sha256",
        "sha384",
        "sha512",
        "sha512/224",
        "sha512/256",
        "sha3-224",
        "sha3-256",
        "sha3-384",
        "sha3-512",
        "ssdeep",
        "imphash",
        "telfhash",
        "impfuzzy",
        "authentihash",
        "vhash",
        "pehash",
        "tlsh",
        "cdhash",
        "filename",
        "filename|md5",
        "filename|sha1",
        "filename|sha224",
        "filename|sha256",
        "filename|sha384",
        "filename|sha512",
        "filename|sha512/224",
        "filename|sha512/256",
        "filename|sha3-224",
        "filename|sha3-256",
        "filename|sha3-384",
        "filename|sha3-512",
        "filename|authentihash",
        "filename|vhash",
        "filename|ssdeep",
        "filename|tlsh",
        "filename|imphash",
        "filename|impfuzzy",
        "filename|pehash",
        "mac-address",
        "mac-eui-64",
        "ip-src",
        "ip-dst",
        "ip-dst|port",
        "ip-src|port",
        "hostname",
        "domain",
        "email",
        "email-src",
        "email-dst",
        "email-subject",
        "email-attachment",
        "email-body",
        "url",
        "user-agent",
        "AS",
        "pattern-in-file",
        "pattern-in-traffic",
        "filename-pattern",
        "stix2-pattern",
        "yara",
        "sigma",
        "mime-type",
        "attachment",
        "malware-sample",
        "link",
        "malware-type",
        "comment",
        "text",
        "hex",
        "vulnerability",
        "cpe",
        "weakness",
        "x509-fingerprint-sha1",
        "x509-fingerprint-md5",
        "x509-fingerprint-sha256",
        "ja3-fingerprint-md5",
        "jarm-fingerprint",
        "hassh-md5",
        "hasshserver-md5",
        "other",
        "hostname|port",
        "email-dst-display-name",
        "email-src-display-name",
        "email-header",
        "email-reply-to",
        "email-x-mailer",
        "email-mime-boundary",
        "email-thread-index",
        "email-message-id",
        "azure-application-id",
        "mobile-application-id",
        "chrome-extension-id",
        "whois-registrant-email",
        "anonymised",
    ]
    ARTIFACTS_DROPPED: Annotated[list[str], Field(alias="Artifacts dropped")] = [
        "md5",
        "sha1",
        "sha224",
        "sha256",
        "sha384",
        "sha512",
        "sha512/224",
        "sha512/256",
        "sha3-224",
        "sha3-256",
        "sha3-384",
        "sha3-512",
        "ssdeep",
        "imphash",
        "telfhash",
        "impfuzzy",
        "authentihash",
        "vhash",
        "cdhash",
        "filename",
        "filename|md5",
        "filename|sha1",
        "filename|sha224",
        "filename|sha256",
        "filename|sha384",
        "filename|sha512",
        "filename|sha512/224",
        "filename|sha512/256",
        "filename|sha3-224",
        "filename|sha3-256",
        "filename|sha3-384",
        "filename|sha3-512",
        "filename|authentihash",
        "filename|vhash",
        "filename|ssdeep",
        "filename|tlsh",
        "filename|imphash",
        "filename|impfuzzy",
        "filename|pehash",
        "regkey",
        "regkey|value",
        "pattern-in-file",
        "pattern-in-memory",
        "filename-pattern",
        "pdb",
        "stix2-pattern",
        "yara",
        "sigma",
        "attachment",
        "malware-sample",
        "named pipe",
        "mutex",
        "process-state",
        "windows-scheduled-task",
        "windows-service-name",
        "windows-service-displayname",
        "comment",
        "text",
        "hex",
        "x509-fingerprint-sha1",
        "x509-fingerprint-md5",
        "x509-fingerprint-sha256",
        "other",
        "cookie",
        "gene",
        "kusto-query",
        "mime-type",
        "anonymised",
        "pgp-public-key",
        "pgp-private-key",
    ]
    PAYLOAD_INSTALLATION: Annotated[list[str], Field(alias="Payload installation")] = [
        "md5",
        "sha1",
        "sha224",
        "sha256",
        "sha384",
        "sha512",
        "sha512/224",
        "sha512/256",
        "sha3-224",
        "sha3-256",
        "sha3-384",
        "sha3-512",
        "ssdeep",
        "imphash",
        "telfhash",
        "impfuzzy",
        "authentihash",
        "vhash",
        "pehash",
        "tlsh",
        "cdhash",
        "filename",
        "filename|md5",
        "filename|sha1",
        "filename|sha224",
        "filename|sha256",
        "filename|sha384",
        "filename|sha512",
        "filename|sha512/224",
        "filename|sha512/256",
        "filename|sha3-224",
        "filename|sha3-256",
        "filename|sha3-384",
        "filename|sha3-512",
        "filename|authentihash",
        "filename|vhash",
        "filename|ssdeep",
        "filename|tlsh",
        "filename|imphash",
        "filename|impfuzzy",
        "filename|pehash",
        "pattern-in-file",
        "pattern-in-traffic",
        "pattern-in-memory",
        "filename-pattern",
        "stix2-pattern",
        "yara",
        "sigma",
        "vulnerability",
        "cpe",
        "weakness",
        "attachment",
        "malware-sample",
        "malware-type",
        "comment",
        "text",
        "hex",
        "x509-fingerprint-sha1",
        "x509-fingerprint-md5",
        "x509-fingerprint-sha256",
        "azure-application-id",
        "azure-application-id",
        "mobile-application-id",
        "chrome-extension-id",
        "other",
        "mime-type",
        "anonymised",
    ]
    PERSISTENCE_MECHANISM: Annotated[list[str], Field(alias="Persistence mechanism")] = [
        "filename",
        "regkey",
        "regkey|value",
        "comment",
        "text",
        "other",
        "hex",
        "anonymised",
    ]
    NETWORK_ACTIVITY: Annotated[list[str], Field(alias="Network activity")] = [
        "ip-src",
        "ip-dst",
        "ip-dst|port",
        "ip-src|port",
        "port",
        "hostname",
        "domain",
        "domain|ip",
        "mac-address",
        "mac-eui-64",
        "email",
        "email-dst",
        "email-src",
        "eppn",
        "url",
        "uri",
        "user-agent",
        "http-method",
        "AS",
        "snort",
        "pattern-in-file",
        "filename-pattern",
        "stix2-pattern",
        "pattern-in-traffic",
        "attachment",
        "comment",
        "text",
        "x509-fingerprint-md5",
        "x509-fingerprint-sha1",
        "x509-fingerprint-sha256",
        "ja3-fingerprint-md5",
        "jarm-fingerprint",
        "hassh-md5",
        "hasshserver-md5",
        "other",
        "hex",
        "cookie",
        "hostname|port",
        "bro",
        "zeek",
        "anonymised",
        "community-id",
        "email-subject",
        "favicon-mmh3",
        "dkim",
        "dkim-signature",
        "ssh-fingerprint",
    ]
    PAYLOAD_TYPE: Annotated[list[str], Field(alias="Payload type")] = ["comment", "text", "other", "anonymised"]
    ATTRIBUTION: Annotated[list[str], Field(alias="Attribution")] = [
        "threat-actor",
        "campaign-name",
        "campaign-id",
        "whois-registrant-phone",
        "whois-registrant-email",
        "whois-registrant-name",
        "whois-registrant-org",
        "whois-registrar",
        "whois-creation-date",
        "comment",
        "text",
        "x509-fingerprint-sha1",
        "x509-fingerprint-md5",
        "x509-fingerprint-sha256",
        "other",
        "dns-soa-email",
        "anonymised",
        "email",
    ]
    EXTERNAL_ANALYSIS: Annotated[list[str], Field(alias="External analysis")] = [
        "md5",
        "sha1",
        "sha256",
        "sha3-224",
        "sha3-256",
        "sha3-384",
        "sha3-512",
        "filename",
        "filename|md5",
        "filename|sha1",
        "filename|sha256",
        "filename|sha3-224",
        "filename|sha3-256",
        "filename|sha3-384",
        "filename|sha3-512",
        "ip-src",
        "ip-dst",
        "ip-dst|port",
        "ip-src|port",
        "mac-address",
        "mac-eui-64",
        "hostname",
        "domain",
        "domain|ip",
        "url",
        "user-agent",
        "regkey",
        "regkey|value",
        "AS",
        "snort",
        "bro",
        "zeek",
        "pattern-in-file",
        "pattern-in-traffic",
        "pattern-in-memory",
        "filename-pattern",
        "vulnerability",
        "cpe",
        "weakness",
        "attachment",
        "malware-sample",
        "link",
        "comment",
        "text",
        "x509-fingerprint-sha1",
        "x509-fingerprint-md5",
        "x509-fingerprint-sha256",
        "ja3-fingerprint-md5",
        "jarm-fingerprint",
        "hassh-md5",
        "hasshserver-md5",
        "github-repository",
        "other",
        "cortex",
        "anonymised",
        "community-id",
    ]
    FINANCIAL_FRAUD: Annotated[list[str], Field(alias="Financial fraud")] = [
        "btc",
        "dash",
        "xmr",
        "iban",
        "bic",
        "bank-account-nr",
        "aba-rtn",
        "bin",
        "cc-number",
        "prtn",
        "phone-number",
        "comment",
        "text",
        "other",
        "hex",
        "anonymised",
    ]
    SUPPORT_TOOL: Annotated[list[str], Field(alias="Support tool")] = [
        "link",
        "text",
        "attachment",
        "comment",
        "other",
        "hex",
        "anonymised",
    ]
    SOCIAL_NETWORK: Annotated[list[str], Field(alias="Social network")] = [
        "github-username",
        "github-repository",
        "github-organisation",
        "jabber-id",
        "twitter-id",
        "email",
        "email-src",
        "email-dst",
        "eppn",
        "comment",
        "text",
        "other",
        "whois-registrant-email",
        "anonymised",
        "pgp-public-key",
        "pgp-private-key",
    ]
    PERSON: Annotated[list[str], Field(alias="Person")] = [
        "first-name",
        "middle-name",
        "last-name",
        "full-name",
        "date-of-birth",
        "place-of-birth",
        "gender",
        "passport-number",
        "passport-country",
        "passport-expiration",
        "redress-number",
        "nationality",
        "visa-number",
        "issue-date-of-the-visa",
        "primary-residence",
        "country-of-residence",
        "special-service-request",
        "frequent-flyer-number",
        "travel-details",
        "payment-details",
        "place-port-of-original-embarkation",
        "place-port-of-clearance",
        "place-port-of-onward-foreign-destination",
        "passenger-name-record-locator-number",
        "comment",
        "text",
        "other",
        "phone-number",
        "identity-card-number",
        "anonymised",
        "email",
        "pgp-public-key",
        "pgp-private-key",
    ]
    OTHER: Annotated[list[str], Field(alias="Other")] = [
        "comment",
        "text",
        "other",
        "size-in-bytes",
        "counter",
        "datetime",
        "cpe",
        "port",
        "float",
        "hex",
        "phone-number",
        "boolean",
        "anonymised",
        "pgp-public-key",
        "pgp-private-key",
    ]


class GetDescribeTypesDescribeTypesAttributes(BaseModel):
    # "name": "default_category, to_ids"
    sane_defaults: dict = {
        "md5": "Payload Delivery, 1",
        "sha1": "Payload Delivery, 1",
        "sha256": "Payload Delivery, 1",
        "filename": "",
        "filename|md5": "",
        "pdb": "",
        "filename|sha1": "",
        "filename|sha256": "",
        "ip-src": "",
        "ip-dst": "",
        "hostname": "",
        "domain": "",
        "domain|ip": "",
        "email": "",
        "email-src": "",
        "eppn": "",
        "email-dst": "",
        "email-subject": "",
        "email-attachment": "",
        "email-body": "",
        "float": "",
        "git-commit-id": "",
        "url": "",
        "http-method": "",
        "user-agent": "",
        "ja3-fingerprint-md5": "",
        "jarm-fingerprint": "",
        "favicon-mmh3": "",
        "hassh-md5": "",
        "hasshserver-md5": "",
        "regkey": "",
        "regkey|value": "",
        "AS": "",
        "snort": "",
        "bro": "",
        "zeek": "",
        "community-id": "",
        "pattern-in-file": "",
        "pattern-in-traffic": "",
        "pattern-in-memory": "",
        "filename-pattern": "",
        "pgp-public-key": "",
        "pgp-private-key": "",
        "ssh-fingerprint": "",
        "yara": "",
        "stix2-pattern": "",
        "sigma": "",
        "gene": "",
        "kusto-query": "",
        "mime-type": "",
        "identity-card-number": "",
        "cookie": "",
        "vulnerability": "",
        "cpe": "",
        "weakness": "",
        "attachment": "",
        "malware-sample": "",
        "link": "",
        "comment": "",
        "text": "",
        "hex": "",
        "other": "",
        "named pipe": "",
        "mutex": "",
        "process-state": "",
        "target-user": "",
        "target-email": "",
        "target-machine": "",
        "target-org": "",
        "target-location": "",
        "target-external": "",
        "btc": "",
        "dash": "",
        "xmr": "",
        "iban": "",
        "bic": "",
        "bank-account-nr": "",
        "aba-rtn": "",
        "bin": "",
        "cc-number": "",
        "prtn": "",
        "phone-number": "",
        "threat-actor": "",
        "campaign-name": "",
        "campaign-id": "",
        "malware-type": "",
        "uri": "",
        "authentihash": "",
        "vhash": "",
        "ssdeep": "",
        "imphash": "",
        "telfhash": "",
        "pehash": "",
        "impfuzzy": "",
        "sha224": "",
        "sha384": "",
        "sha512": "",
        "sha512/224": "",
        "sha512/256": "",
        "sha3-224": "",
        "sha3-256": "",
        "sha3-384": "",
        "sha3-512": "",
        "tlsh": "",
        "cdhash": "",
        "filename|authentihash": "",
        "filename|vhash": "",
        "filename|ssdeep": "",
        "filename|imphash": "",
        "filename|impfuzzy": "",
        "filename|pehash": "",
        "filename|sha224": "",
        "filename|sha384": "",
        "filename|sha512": "",
        "filename|sha512/224": "",
        "filename|sha512/256": "",
        "filename|sha3-224": "",
        "filename|sha3-256": "",
        "filename|sha3-384": "",
        "filename|sha3-512": "",
        "filename|tlsh": "",
        "windows-scheduled-task": "",
        "windows-service-name": "",
        "windows-service-displayname": "",
        "whois-registrant-email": "",
        "whois-registrant-phone": "",
        "whois-registrant-name": "",
        "whois-registrant-org": "",
        "whois-registrar": "",
        "whois-creation-date": "",
        "x509-fingerprint-sha1": "",
        "x509-fingerprint-md5": "",
        "x509-fingerprint-sha256": "",
        "dns-soa-email": "",
        "size-in-bytes": "",
        "counter": "",
        "datetime": "",
        "port": "",
        "ip-dst|port": "",
        "ip-src|port": "",
        "hostname|port": "",
        "mac-address": "",
        "mac-eui-64": "",
        "email-dst-display-name": "",
        "email-src-display-name": "",
        "email-header": "",
        "email-reply-to": "",
        "email-x-mailer": "",
        "email-mime-boundary": "",
        "email-thread-index": "",
        "email-message-id": "",
        "github-username": "",
        "github-repository": "",
        "github-organisation": "",
        "jabber-id": "",
        "twitter-id": "",
        "dkim": "",
        "dkim-signature": "",
        "first-name": "",
        "middle-name": "",
        "last-name": "",
        "full-name": "",
        "date-of-birth": "",
        "place-of-birth": "",
        "gender": "",
        "passport-number": "",
        "passport-country": "",
        "passport-expiration": "",
        "redress-number": "",
        "nationality": "",
        "visa-number": "",
        "issue-date-of-the-visa": "",
        "primary-residence": "",
        "country-of-residence": "",
        "special-service-request": "",
        "frequent-flyer-number": "",
        "travel-details": "",
        "payment-details": "",
        "place-port-of-original-embarkation": "",
        "place-port-of-clearance": "",
        "place-port-of-onward-foreign-destination": "",
        "passenger-name-record-locator-number": "",
        "mobile-application-id": "",
        "azure-application-id": "",
        "chrome-extension-id": "",
        "cortex": "",
        "boolean": "",
        "anonymised": "",
    }

    def bring_sane_defaults_to_correct_format(dictionary: dict):
        for items in dictionary.keys():
            attributes: list[str] = dictionary[items].split(",")
            item_default_category: str = attributes[0]
            if len(attributes) > 1:
                item_to_ids: int = int(attributes[1])
                dictionary[items] = GetDescribeTypesSaneDefaultsAttributes(
                    default_category=item_default_category, to_ids=item_to_ids
                )
            else:
                dictionary[items] = GetDescribeTypesSaneDefaultsAttributes(
                    default_category=item_default_category, to_ids=0
                )

    bring_sane_defaults_to_correct_format(sane_defaults)

    TYPES: Annotated[list[str], Field(alias="types")] = [
        "md5",
        "sha1",
        "sha256",
        "filename",
        "pdb",
        "filename|md5",
        "filename|sha1",
        "filename|sha256",
        "ip-src",
        "ip-dst",
        "hostname",
        "domain",
        "domain|ip",
        "email",
        "email-src",
        "eppn",
        "email-dst",
        "email-subject",
        "email-attachment",
        "email-body",
        "float",
        "git-commit-id",
        "url",
        "http-method",
        "user-agent",
        "ja3-fingerprint-md5",
        "jarm-fingerprint",
        "favicon-mmh3",
        "hassh-md5",
        "hasshserver-md5",
        "regkey",
        "regkey|value",
        "AS",
        "snort",
        "bro",
        "zeek",
        "community-id",
        "pattern-in-file",
        "pattern-in-traffic",
        "pattern-in-memory",
        "filename-pattern",
        "pgp-public-key",
        "pgp-private-key",
        "ssh-fingerprint",
        "yara",
        "stix2-pattern",
        "sigma",
        "gene",
        "kusto-query",
        "mime-type",
        "identity-card-number",
        "cookie",
        "vulnerability",
        "cpe",
        "weakness",
        "attachment",
        "malware-sample",
        "link",
        "comment",
        "text",
        "hex",
        "other",
        "named pipe",
        "mutex",
        "process-state",
        "target-user",
        "target-email",
        "target-machine",
        "target-org",
        "target-location",
        "target-external",
        "btc",
        "dash",
        "xmr",
        "iban",
        "bic",
        "bank-account-nr",
        "aba-rtn",
        "bin",
        "cc-number",
        "prtn",
        "phone-number",
        "threat-actor",
        "campaign-name",
        "campaign-id",
        "malware-type",
        "uri",
        "authentihash",
        "vhash",
        "ssdeep",
        "imphash",
        "telfhash",
        "pehash",
        "impfuzzy",
        "sha224",
        "sha384",
        "sha512",
        "sha512/224",
        "sha512/256",
        "sha3-224",
        "sha3-256",
        "sha3-384",
        "sha3-512",
        "tlsh",
        "cdhash",
        "filename|authentihash",
        "filename|vhash",
        "filename|ssdeep",
        "filename|imphash",
        "filename|impfuzzy",
        "filename|pehash",
        "filename|sha224",
        "filename|sha384",
        "filename|sha512",
        "filename|sha512/224",
        "filename|sha512/256",
        "filename|sha3-224",
        "filename|sha3-256",
        "filename|sha3-384",
        "filename|sha3-512",
        "filename|tlsh",
        "windows-scheduled-task",
        "windows-service-name",
        "windows-service-displayname",
        "whois-registrant-email",
        "whois-registrant-phone",
        "whois-registrant-name",
        "whois-registrant-org",
        "whois-registrar",
        "whois-creation-date",
        "x509-fingerprint-sha1",
        "x509-fingerprint-md5",
        "x509-fingerprint-sha256",
        "dns-soa-email",
        "size-in-bytes",
        "counter",
        "datetime",
        "port",
        "ip-dst|port",
        "ip-src|port",
        "hostname|port",
        "mac-address",
        "mac-eui-64",
        "email-dst-display-name",
        "email-src-display-name",
        "email-header",
        "email-reply-to",
        "email-x-mailer",
        "email-mime-boundary",
        "email-thread-index",
        "email-message-id",
        "github-username",
        "github-repository",
        "github-organisation",
        "jabber-id",
        "twitter-id",
        "dkim",
        "dkim-signature",
        "first-name",
        "middle-name",
        "last-name",
        "full-name",
        "date-of-birth",
        "place-of-birth",
        "gender",
        "passport-number",
        "passport-country",
        "passport-expiration",
        "redress-number",
        "nationality",
        "visa-number",
        "issue-date-of-the-visa",
        "primary-residence",
        "country-of-residence",
        "special-service-request",
        "frequent-flyer-number",
        "travel-details",
        "payment-details",
        "place-port-of-original-embarkation",
        "place-port-of-clearance",
        "place-port-of-onward-foreign-destination",
        "passenger-name-record-locator-number",
        "mobile-application-id",
        "azure-application-id",
        "chrome-extension-id",
        "cortex",
        "boolean",
        "anonymised",
    ]
    CATEGORIES: Annotated[list[str], Field(alias="categories")] = [
        "Internal reference",
        "Targeting data",
        "Antivirus detection",
        "Payload delivery",
        "Artifacts dropped",
        "Payload installation",
        "Persistence mechanism",
        "Network activity",
        "Payload type",
        "Attribution",
        "External analysis",
        "Financial fraud",
        "Support Tool",
        "Social network",
        "Person",
        "Other",
    ]
    CATEGORY_TYPE_MAPPINGS: Annotated[GetDescribeTypesCategoryTypeMappings, Field(alias="category_type_mappings")]


class GetDescribeTypesResponse(BaseModel):
    result: GetDescribeTypesDescribeTypesAttributes

    class Config:
        orm_mode = True
