"""align database to misp

Revision ID: 0600d41b7e3d
Revises: e658480768f6
Create Date: 2026-08-06 11:01:39.120514

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0600d41b7e3d"
down_revision = "e658480768f6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_template_object_dependencies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_template_id", sa.Integer(), nullable=False),
        sa.Column("object_template_uuid", sa.String(length=40), nullable=False),
        sa.Column("object_template_name", sa.String(length=255), nullable=False),
        sa.Column("minimum_version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_template_object_dependencies")),
    )
    op.create_table(
        "event_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("creator_user_id", sa.Integer(), nullable=False),
        sa.Column("distribution", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("exposed", sa.Boolean(), nullable=False),
        sa.Column("misp_default", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_templates")),
    )
    with op.batch_alter_table("event_templates", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_event_templates_uuid"), ["uuid"], unique=False)

    with op.batch_alter_table("admin_settings", schema=None) as batch_op:
        batch_op.drop_constraint("uq_admin_settings_setting", type_="unique")
        batch_op.create_index(batch_op.f("ix_admin_settings_setting"), ["setting"], unique=False)

    with op.batch_alter_table("attributes", schema=None) as batch_op:
        batch_op.drop_constraint("uq_attributes_uuid", type_="unique")
        batch_op.create_index(batch_op.f("ix_attributes_uuid"), ["uuid"], unique=False)

    with op.batch_alter_table("collection_elements", schema=None) as batch_op:
        batch_op.drop_constraint("uq_collection_elements_uuid", type_="unique")
        batch_op.drop_constraint("uq_collection_elements_element_uuid_collection_id", type_="unique")
        batch_op.create_index(
            "uq_collection_elements_element_uuid_collection_id", ["element_uuid", "collection_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_collection_elements_uuid"), ["uuid"], unique=False)

    with op.batch_alter_table("collections", schema=None) as batch_op:
        batch_op.add_column(sa.Column("locked", sa.Boolean(), nullable=False))
        batch_op.drop_constraint("uq_collections_uuid", type_="unique")
        batch_op.create_index("ix_collections_uuid", ["uuid"], unique=False)

    with op.batch_alter_table("correlation_exclusions", schema=None) as batch_op:
        batch_op.drop_constraint("uq_correlation_exclusions_value", type_="unique")
        batch_op.drop_index("ix_correlation_exclusions_value")
        batch_op.create_index("ix_correlation_exclusions_value", ["value"], unique=False)

    with op.batch_alter_table("correlation_values", schema=None) as batch_op:
        batch_op.drop_constraint("uq_correlation_values_value", type_="unique")
        batch_op.drop_index("ix_correlation_values_value")
        batch_op.create_index("ix_correlation_values_value", ["value"], unique=False)

    with op.batch_alter_table("dashboards", schema=None) as batch_op:
        batch_op.drop_constraint("uq_dashboards_uuid", type_="unique")
        batch_op.create_index("ix_dashboards_uuid", ["uuid"], unique=False)

    with op.batch_alter_table("default_correlations", schema=None) as batch_op:
        batch_op.drop_constraint("uq_default_correlations_unique_correlation", type_="unique")
        batch_op.create_index(
            "ix_default_correlations_unique_correlation", ["attribute_id", "1_attribute_id", "value_id"], unique=False
        )

    with op.batch_alter_table("event_blocklists", schema=None) as batch_op:
        batch_op.drop_constraint("uq_event_blocklists_event_uuid", type_="unique")
        batch_op.create_index("ix_event_blocklists_event_uuid", ["event_uuid"], unique=False)

    with op.batch_alter_table("event_reports", schema=None) as batch_op:
        batch_op.drop_constraint("uq_event_reports_uuid", type_="unique")
        batch_op.create_index("ix_event_reports_uuid", ["uuid"], unique=False)

    # Drop the FK on shadow_attributes that references events.uuid before
    # dropping the index backing it (MySQL requires the index for the FK).
    with op.batch_alter_table("shadow_attributes", schema=None) as batch_op:
        batch_op.drop_constraint("fk_shadow_attributes_event_uuid_events", type_="foreignkey")

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_constraint("uq_events_uuid", type_="unique")
        batch_op.drop_index("ix_events_uuid")
        batch_op.create_index("ix_events_uuid", ["uuid"], unique=False)

    # Recreate the FK now that the index exists again.
    with op.batch_alter_table("shadow_attributes", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_shadow_attributes_event_uuid_events",
            "events",
            ["event_uuid"],
            ["uuid"],
        )

    with op.batch_alter_table("galaxies", schema=None) as batch_op:
        batch_op.drop_constraint("uq_galaxies_uuid", type_="unique")
        batch_op.create_index("ix_galaxies_uuid", ["uuid"], unique=False)

    with op.batch_alter_table("galaxy_clusters", schema=None) as batch_op:
        batch_op.alter_column("description", existing_type=sa.TEXT(), nullable=True)

    with op.batch_alter_table("inbox", schema=None) as batch_op:
        batch_op.drop_constraint("uq_inbox_uuid", type_="unique")
        batch_op.create_index("ix_inbox_uuid", ["uuid"], unique=False)

    with op.batch_alter_table("no_acl_correlations", schema=None) as batch_op:
        batch_op.drop_constraint("uq_no_acl_correlations_unique_correlation", type_="unique")
        batch_op.create_index(batch_op.f("ix_no_acl_correlations_1_attribute_id"), ["1_attribute_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_no_acl_correlations_attribute_id"), ["attribute_id"], unique=False)
        batch_op.create_index(
            "ix_no_acl_correlations_unique_correlation", ["attribute_id", "1_attribute_id", "value_id"], unique=False
        )

    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.drop_constraint("uq_notes_uuid", type_="unique")
        batch_op.create_index("ix_notes_uuid", ["uuid"], unique=False)

    with op.batch_alter_table("object_references", schema=None) as batch_op:
        batch_op.drop_constraint("uq_object_references_uuid", type_="unique")
        batch_op.create_index("ix_object_references_uuid", ["uuid"], unique=False)

    with op.batch_alter_table("objects", schema=None) as batch_op:
        batch_op.drop_index("ix_objects_name")
        batch_op.drop_constraint("uq_objects_uuid", type_="unique")
        batch_op.create_index("ix_objects_uuid", ["uuid"], unique=False)

    with op.batch_alter_table("opinions", schema=None) as batch_op:
        batch_op.drop_constraint("uq_opinions_uuid", type_="unique")
        batch_op.create_index("ix_opinions_uuid", ["uuid"], unique=False)

    with op.batch_alter_table("org_blocklists", schema=None) as batch_op:
        batch_op.drop_constraint("uq_org_blocklists_org_uuid", type_="unique")
        batch_op.create_index("ix_org_blocklists_org_uuid", ["org_uuid"], unique=False)

    with op.batch_alter_table("organisations", schema=None) as batch_op:
        batch_op.drop_constraint("uq_organisations_name", type_="unique")
        batch_op.drop_constraint("uq_organisations_uuid", type_="unique")
        batch_op.create_index("ix_organisations_name", ["name"], unique=True)
        batch_op.create_index("ix_organisations_uuid", ["uuid"], unique=False)

    with op.batch_alter_table("over_correlating_values", schema=None) as batch_op:
        batch_op.drop_constraint("uq_over_correlating_values_value", type_="unique")
        batch_op.drop_index("ix_over_correlating_values_value")
        batch_op.create_index("ix_over_correlating_values_value", ["value"], unique=False)

    with op.batch_alter_table("relationships", schema=None) as batch_op:
        batch_op.drop_constraint("uq_relationships_uuid", type_="unique")
        batch_op.create_index("ix_relationships_uuid", ["uuid"], unique=False)

    with op.batch_alter_table("servers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("push_collections", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("pull_collections", sa.Boolean(), nullable=False))

    with op.batch_alter_table("sharing_groups", schema=None) as batch_op:
        batch_op.drop_constraint("uq_sharing_groups_name", type_="unique")
        batch_op.drop_constraint("uq_sharing_groups_uuid", type_="unique")
        batch_op.create_index("ix_sharing_groups_name", ["name"], unique=True)
        batch_op.create_index("ix_sharing_groups_uuid", ["uuid"], unique=False)

    with op.batch_alter_table("sightings", schema=None) as batch_op:
        batch_op.drop_constraint("uq_sightings_uuid", type_="unique")
        batch_op.create_index("ix_sightings_uuid", ["uuid"], unique=False)

    with op.batch_alter_table("tag_collections", schema=None) as batch_op:
        batch_op.drop_constraint("uq_tag_collections_uuid", type_="unique")
        batch_op.create_index("ix_tag_collections_uuid", ["uuid"], unique=False)

    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_constraint("uq_tags_name", type_="unique")
        batch_op.create_index("ix_tags_name", ["name"], unique=True)

    with op.batch_alter_table("taxii_servers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("enabled", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("auth_type", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("discovery_url", sa.String(length=512), nullable=True))
        batch_op.alter_column("api_root", existing_type=sa.VARCHAR(length=191), nullable=True)
        batch_op.create_index("ix_taxii_servers_baseurl", ["discovery_url"], unique=False)
        batch_op.drop_column("baseurl")

    with op.batch_alter_table("user_login_profiles", schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_login_profiles_hash", type_="unique")
        batch_op.create_index("ix_user_login_profiles_hash", ["hash"], unique=False)

    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_settings_user_id_setting", type_="unique")
        batch_op.create_index("ix_user_settings_user_id_setting", ["user_id", "setting"], unique=True)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("uq_users_email", type_="unique")
        batch_op.drop_constraint("uq_users_sub", type_="unique")
        batch_op.create_index("ix_users_email", ["email"], unique=True)
        batch_op.create_index("ix_users_sub", ["sub"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index("ix_users_sub")
        batch_op.drop_index("ix_users_email")
        batch_op.create_unique_constraint("uq_users_sub", ["sub"])
        batch_op.create_unique_constraint("uq_users_email", ["email"])

    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.drop_index("ix_user_settings_user_id_setting")
        batch_op.create_unique_constraint("uq_user_settings_user_id_setting", ["user_id", "setting"])

    with op.batch_alter_table("user_login_profiles", schema=None) as batch_op:
        batch_op.drop_index("ix_user_login_profiles_hash")
        batch_op.create_unique_constraint("uq_user_login_profiles_hash", ["hash"])

    with op.batch_alter_table("taxii_servers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("baseurl", sa.VARCHAR(length=191), nullable=False))
        batch_op.drop_index("ix_taxii_servers_baseurl")
        batch_op.alter_column("api_root", existing_type=sa.VARCHAR(length=191), nullable=False)
        batch_op.drop_column("discovery_url")
        batch_op.drop_column("auth_type")
        batch_op.drop_column("enabled")

    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_index("ix_tags_name")
        batch_op.create_unique_constraint("uq_tags_name", ["name"])

    with op.batch_alter_table("tag_collections", schema=None) as batch_op:
        batch_op.drop_index("ix_tag_collections_uuid")
        batch_op.create_unique_constraint("uq_tag_collections_uuid", ["uuid"])

    with op.batch_alter_table("sightings", schema=None) as batch_op:
        batch_op.drop_index("ix_sightings_uuid")
        batch_op.create_unique_constraint("uq_sightings_uuid", ["uuid"])

    with op.batch_alter_table("sharing_groups", schema=None) as batch_op:
        batch_op.drop_index("ix_sharing_groups_uuid")
        batch_op.drop_index("ix_sharing_groups_name")
        batch_op.create_unique_constraint("uq_sharing_groups_uuid", ["uuid"])
        batch_op.create_unique_constraint("uq_sharing_groups_name", ["name"])

    with op.batch_alter_table("servers", schema=None) as batch_op:
        batch_op.drop_column("pull_collections")
        batch_op.drop_column("push_collections")

    with op.batch_alter_table("relationships", schema=None) as batch_op:
        batch_op.drop_index("ix_relationships_uuid")
        batch_op.create_unique_constraint("uq_relationships_uuid", ["uuid"])

    with op.batch_alter_table("over_correlating_values", schema=None) as batch_op:
        batch_op.drop_index("ix_over_correlating_values_value")
        batch_op.create_index("ix_over_correlating_values_value", ["value"], unique=False)
        batch_op.create_unique_constraint("uq_over_correlating_values_value", ["value"])

    with op.batch_alter_table("organisations", schema=None) as batch_op:
        batch_op.drop_index("ix_organisations_uuid")
        batch_op.drop_index("ix_organisations_name")
        batch_op.create_unique_constraint("uq_organisations_uuid", ["uuid"])
        batch_op.create_unique_constraint("uq_organisations_name", ["name"])

    with op.batch_alter_table("org_blocklists", schema=None) as batch_op:
        batch_op.drop_index("ix_org_blocklists_org_uuid")
        batch_op.create_unique_constraint("uq_org_blocklists_org_uuid", ["org_uuid"])

    with op.batch_alter_table("opinions", schema=None) as batch_op:
        batch_op.drop_index("ix_opinions_uuid")
        batch_op.create_unique_constraint("uq_opinions_uuid", ["uuid"])

    with op.batch_alter_table("objects", schema=None) as batch_op:
        batch_op.drop_index("ix_objects_uuid")
        batch_op.create_unique_constraint("uq_objects_uuid", ["uuid"])
        batch_op.create_index("ix_objects_name", ["name"], unique=False)

    with op.batch_alter_table("object_references", schema=None) as batch_op:
        batch_op.drop_index("ix_object_references_uuid")
        batch_op.create_unique_constraint("uq_object_references_uuid", ["uuid"])

    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.drop_index("ix_notes_uuid")
        batch_op.create_unique_constraint("uq_notes_uuid", ["uuid"])

    with op.batch_alter_table("no_acl_correlations", schema=None) as batch_op:
        batch_op.drop_index("ix_no_acl_correlations_unique_correlation")
        batch_op.drop_index(batch_op.f("ix_no_acl_correlations_attribute_id"))
        batch_op.drop_index(batch_op.f("ix_no_acl_correlations_1_attribute_id"))
        batch_op.create_unique_constraint(
            "uq_no_acl_correlations_unique_correlation", ["attribute_id", "1_attribute_id", "value_id"]
        )

    with op.batch_alter_table("inbox", schema=None) as batch_op:
        batch_op.drop_index("ix_inbox_uuid")
        batch_op.create_unique_constraint("uq_inbox_uuid", ["uuid"])

    with op.batch_alter_table("galaxy_clusters", schema=None) as batch_op:
        batch_op.alter_column("description", existing_type=sa.TEXT(), nullable=False)

    with op.batch_alter_table("galaxies", schema=None) as batch_op:
        batch_op.drop_index("ix_galaxies_uuid")
        batch_op.create_unique_constraint("uq_galaxies_uuid", ["uuid"])

    # Drop the FK on shadow_attributes that references events.uuid before
    # dropping the index backing it (MySQL requires the index for the FK).
    with op.batch_alter_table("shadow_attributes", schema=None) as batch_op:
        batch_op.drop_constraint("fk_shadow_attributes_event_uuid_events", type_="foreignkey")

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index("ix_events_uuid")
        batch_op.create_index("ix_events_uuid", ["uuid"], unique=False)
        batch_op.create_unique_constraint("uq_events_uuid", ["uuid"])

    # Recreate the FK now that the index exists again.
    with op.batch_alter_table("shadow_attributes", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_shadow_attributes_event_uuid_events",
            "events",
            ["event_uuid"],
            ["uuid"],
        )

    with op.batch_alter_table("event_reports", schema=None) as batch_op:
        batch_op.drop_index("ix_event_reports_uuid")
        batch_op.create_unique_constraint("uq_event_reports_uuid", ["uuid"])

    with op.batch_alter_table("event_blocklists", schema=None) as batch_op:
        batch_op.drop_index("ix_event_blocklists_event_uuid")
        batch_op.create_unique_constraint("uq_event_blocklists_event_uuid", ["event_uuid"])

    with op.batch_alter_table("default_correlations", schema=None) as batch_op:
        batch_op.drop_index("ix_default_correlations_unique_correlation")
        batch_op.create_unique_constraint(
            "uq_default_correlations_unique_correlation", ["attribute_id", "1_attribute_id", "value_id"]
        )

    with op.batch_alter_table("dashboards", schema=None) as batch_op:
        batch_op.drop_index("ix_dashboards_uuid")
        batch_op.create_unique_constraint("uq_dashboards_uuid", ["uuid"])

    with op.batch_alter_table("correlation_values", schema=None) as batch_op:
        batch_op.drop_index("ix_correlation_values_value")
        batch_op.create_index("ix_correlation_values_value", ["value"], unique=False)
        batch_op.create_unique_constraint("uq_correlation_values_value", ["value"])

    with op.batch_alter_table("correlation_exclusions", schema=None) as batch_op:
        batch_op.drop_index("ix_correlation_exclusions_value")
        batch_op.create_index("ix_correlation_exclusions_value", ["value"], unique=False)
        batch_op.create_unique_constraint("uq_correlation_exclusions_value", ["value"])

    with op.batch_alter_table("collections", schema=None) as batch_op:
        batch_op.drop_index("ix_collections_uuid")
        batch_op.create_unique_constraint("uq_collections_uuid", ["uuid"])
        batch_op.drop_column("locked")

    with op.batch_alter_table("collection_elements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_collection_elements_uuid"))
        batch_op.drop_index("uq_collection_elements_element_uuid_collection_id")
        batch_op.create_unique_constraint(
            "uq_collection_elements_element_uuid_collection_id", ["element_uuid", "collection_id"]
        )
        batch_op.create_unique_constraint("uq_collection_elements_uuid", ["uuid"])

    with op.batch_alter_table("attributes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attributes_uuid"))
        batch_op.create_unique_constraint("uq_attributes_uuid", ["uuid"])

    with op.batch_alter_table("admin_settings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_admin_settings_setting"))
        batch_op.create_unique_constraint("uq_admin_settings_setting", ["setting"])

    with op.batch_alter_table("event_templates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_templates_uuid"))

    op.drop_table("event_templates")
    op.drop_table("event_template_object_dependencies")
    # ### end Alembic commands ###
