from pydantic import BaseModel


class AttributeStatisticsResponse(BaseModel):
    AS: int
    attachment: int
    authentihash: int
    boolean: int
    btc: int
    campaign_id: int
    campaign_name: int
    comment: int
    cookie: int
    counter: int
    cpe: int
    date_of_birth: int
    datetime: int
    dns_soa_email: int
    domain: int
    domain_ip: int
    email: int
    email_attachment: int
    email_body: int
    email_dst: int
    email_message_id: int
    email_mime_boundary: int
    email_reply_to: int
    email_src: int
    email_src_display_name: int
    email_subject: int
    email_x_mailer: int
    filename: int
    filename_pattern: int
    filename_md5: int
    filename_sha1: int
    filename_sha256: int
    first_name: int
    float: int
    full_name: int
    gender: int
    github_repository: int
    github_username: int
    hex: int
    hostname: int
    http_method: int
    imphash: int
    ip_dst: int
    ip_dst_port: int
    ip_src: int
    ip_src_port: int
    ja3_fingerprint_md5: int
    jabber_id: int
    jarm_fingerprint: int
    last_name: int
    link: int
    malware_sample: int
    md5: int
    mime_type: int
    mobile_application_id: int
    mutex: int
    named_pipe: int
    nationality: int
    other: int
    passport_country: int
    passport_expiration: int
    passport_number: int
    pattern_in_file: int
    pattern_in_memory: int
    pattern_in_traffic: int
    pdb: int
    pehash: int
    phone_number: int
    place_of_birth: int
    port: int
    regkey: int
    regkey_value: int
    sha1: int
    sha224: int
    sha256: int
    sha384: int
    sha512: int
    sigma: int
    size_in_bytes: int
    snort: int
    ssdeep: int
    stix2_pattern: int
    target_external: int
    target_location: int
    target_machine: int
    target_org: int
    target_user: int
    text: int
    threat_actor: int
    tlsh: int
    uri: int
    url: int
    user_agent: int
    vhash: int
    vulnerability: int
    weakness: int
    whois_creation_date: int
    whois_registrant_email: int
    whois_registrant_name: int
    whois_registrant_org: int
    whois_registrant_phone: int
    whois_registrar: int
    windows_scheduled_task: int
    windows_service_name: int
    x509_fingerprint_md5: int
    x509_fingerprint_sha1: int
    x509_fingerprint_sha256: int
    yara: int

    class Config:
        orm_mode = True
