from pydantic import BaseModel


class AttributeStatisticsResponse(BaseModel):
    AS: str
    attachment: str
    authentihash: str
    boolean: str
    btc: str
    campaign_id: str
    campaign_name: str
    comment: str
    cookie: str
    counter: str
    cpe: str
    date_of_birth: str
    datetime: str
    dns_soa_email: str
    domain: str
    domain_ip: str
    email: str
    email_attachment: str
    email_body: str
    email_dst: str
    email_message_id: str
    email_mime_boundary: str
    email_reply_to: str
    email_src: str
    email_src_display_name: str
    email_subject: str
    email_x_mailer: str
    filename: str
    filename_pattern: str
    filename_md5: str
    filename_sha1: str
    filename_sha256: str
    first_name: str
    float: str
    full_name: str
    gender: str
    github_repository: str
    github_username: str
    hex: str
    hostname: str
    http_method: str
    imphash: str
    ip_dst: str
    ip_dst_port: str
    ip_src: str
    ip_src_port: str
    ja3_fingerprstr_md5: str
    jabber_id: str
    jarm_fingerprstr: str
    last_name: str
    link: str
    malware_sample: str
    md5: str
    mime_type: str
    mobile_application_id: str
    mutex: str
    named_pipe: str
    nationality: str
    other: str
    passport_country: str
    passport_expiration: str
    passport_number: str
    pattern_in_file: str
    pattern_in_memory: str
    pattern_in_traffic: str
    pdb: str
    pehash: str
    phone_number: str
    place_of_birth: str
    port: str
    regkey: str
    regkey_value: str
    sha1: str
    sha224: str
    sha256: str
    sha384: str
    sha512: str
    sigma: str
    size_in_bytes: str
    snort: str
    ssdeep: str
    stix2_pattern: str
    target_external: str
    target_location: str
    target_machine: str
    target_org: str
    target_user: str
    text: str
    threat_actor: str
    tlsh: str
    uri: str
    url: str
    user_agent: str
    vhash: str
    vulnerability: str
    weakness: str
    whois_creation_date: str
    whois_registrant_email: str
    whois_registrant_name: str
    whois_registrant_org: str
    whois_registrant_phone: str
    whois_registrar: str
    windows_scheduled_task: str
    windows_service_name: str
    x509_fingerprstr_md5: str
    x509_fingerprstr_sha1: str
    x509_fingerprstr_sha256: str
    yara: str

    class Config:
        orm_mode = True
